# Generated by Django 3.0.7 on 2020-09-22 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0004_auto_20200921_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon',
            name='saloon_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 9, 22, 8, 31, 32, 270409, tzinfo=utc)),
        ),
    ]
