# Generated by Django 3.0.7 on 2020-10-13 07:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0005_auto_20201011_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 10, 13, 7, 29, 42, 786074, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saloon.ClientAccount')),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saloon.Saloon')),
            ],
        ),
    ]
