# Generated by Django 3.0.7 on 2020-09-25 08:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0007_auto_20200924_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloonservice',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 9, 25, 8, 45, 42, 12010, tzinfo=utc)),
        ),
    ]
