# Generated by Django 3.0.7 on 2020-10-13 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0007_auto_20201013_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 10, 13, 15, 23, 50, 831094, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
