# Generated by Django 3.0.7 on 2020-09-25 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0008_auto_20200925_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='price',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 9, 25, 9, 42, 10, 688699, tzinfo=utc)),
        ),
    ]
