# Generated by Django 3.0.7 on 2020-10-09 07:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0011_auto_20201007_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 7, 36, 36, 948399, tzinfo=utc)),
        ),
    ]
