# Generated by Django 3.0.7 on 2020-10-09 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0012_auto_20201009_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 13, 55, 48, 506387, tzinfo=utc)),
        ),
    ]
